### ISSUE TITLE
Not compatible to Illuminate\Support\Collection

### ISSUE THREAD

**Issue by kkrieger85** [artkonekt/menu#3]
Declaration of Konekt\Menu\ItemCollection::add(Konekt\Menu\Item $item) should be compatible with Illuminate\Support\Collection::add($item)

This error occurs on installation of https://github.com/vanilophp/framework

Please see https://github.com/vanilophp/framework/issues/39

Maybe it's because of differente laravel/framework version.

**Comment by fulopattila122** [comment]
Originally caused by laravel/framework#27082. Looks like an undocumented BC. At least in our case it is.

**Comment by fulopattila122** [comment]
Fix for this has been released in `v1.3.0`
