### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by tobiasnitsche** [artkonekt/menu#6]
Hi there!

Are there any plan to update to Laravel 9? Its the only package which is left on our system to update to Laravel 9.

Cheers,
 Tobias

**Comment by fulopattila122** [comment]
Yep, thanks for the ping. I do it shortly, it'll be released today

**Comment by fulopattila122** [comment]
Version 1.9.0 supports both Laravel 9 and PHP 8.1

**Comment by tobiasnitsche** [comment]
Thanks for the upgrade. Awesome
