### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by tobiasnitsche** [artkonekt/menu#9]
Hi there!

Are there any plan to update to Laravel 10? Its the only package which is left on our system to update to Laravel 10.

Cheers,
Tobias

**Comment by fulopattila122** [comment]
Coming today ;)

**Comment by fulopattila122** [comment]
@tobiasnitsche upgrade to v1.10 and you should be good to go. Thanks for notifying me!

**Comment by tobiasnitsche** [comment]
Cool! Thanks for the quick support
